spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
  mvc:
    servlet:
      path: / #设置dispatcherServlet路径为默认值
  datasource:
    # 连接到 EDS 服务器上的 mysql
    username: 'hlx_is_1admin'
    password: '#includeAa'
    url: jdbc:mysql://rm-wz9oyu31wovh7q298fo.mysql.rds.aliyuncs.com:3306/pet_collar_pro?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: wall #开启druid数据库底层防火墙功能
      filter:
        wall:
          enabled: true
          config:
            drop-table-allow: false #禁止删除表
  mail:
    host: smtp.163.com #发送邮件服务器
    username: hlx_1612682622@163.com #发送邮件的邮箱地址
    password: NICXBRKRCFQNZOHX #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  jdbc:
    template:
      query-timeout: 3
  redis:
    #连接到 ECS 服务器上的 redis
    host: 120.25.25.52
    port: 6379
    password: inAlieCs953cSustProJect4200
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
#    lettuce:
#      shutdown-timeout: 0
    client-type: jedis
server:
  port: 8082
  error:
    path: /error
  servlet:
    encoding:
      charset: utf-8
      enabled: true

